[build]
  publish = "."

[[headers]]
  for = "/assets/pdfs/*"
  [headers.values]
    Content-Type = "application/pdf"
    Cache-Control = "public, max-age=86400"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
